services:
  frontend:
    build:
      context: client
    container_name: frontend
    working_dir: /usr/src/app
    networks:
      - node-network
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    command: npm start

  server-node:
    build:
      context: server-node
    container_name: backend
    working_dir: /usr/src/app
    networks:
      - node-network
    volumes:
      - ./server-node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - CLIENT_PORT=${CLIENT_PORT
    command: npm start

  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - server-node
      - frontend

networks:
  node-network:
    driver: bridge
